-- MySQL Script generated by MySQL Workbench
-- Wed Nov  5 00:32:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema item
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema item
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `item` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `item` ;

-- -----------------------------------------------------
-- Table `m_item_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m_item_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `m_item_group` (
  `item_group_id` INT NOT NULL,
  `item_group_name` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`item_group_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `m_item_localize`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m_item_localize` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `m_item_localize` (
  `item_id` INT NOT NULL,
  `item_name` VARCHAR(128) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `m_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `m_item` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `m_item` (
  `item_id` INT NOT NULL,
  `item_group_id` INT NOT NULL,
  `rarity` INT NOT NULL,
  `max_possess_count` INT NULL DEFAULT 99,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_m_item_m_item_group1`
    FOREIGN KEY (`item_group_id`)
    REFERENCES `m_item_group` (`item_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_m_item_m_item_localize1`
    FOREIGN KEY (`item_id`)
    REFERENCES `m_item_localize` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_m_item_m_item_group1_idx` ON `m_item` (`item_group_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
