// <auto-generated />
using Api;
using Api.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251101080426_RenameMasterTablesSnakeCase")]
    partial class RenameMasterTablesSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.MItem", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("item_id"));

                    b.Property<byte>("item_type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("max_count")
                        .HasColumnType("int");

                    b.HasKey("item_id");

                    b.ToTable("MItems");
                });

            modelBuilder.Entity("Api.Models.MItemLocalize", b =>
                {
                    b.Property<int>("item_id")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("item_id");

                    b.ToTable("MItemLocalizes");
                });

            modelBuilder.Entity("Api.Models.MItemLocalize", b =>
                {
                    b.HasOne("Api.Models.MItem", null)
                        .WithMany()
                        .HasForeignKey("item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
