// <auto-generated />
using System;
using Api.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251105175953_SeedWithHasData")]
    partial class SeedWithHasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Item.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPossessCount")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("ItemId");

                    b.HasIndex("ItemGroupId");

                    b.ToTable("m_item", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500),
                            ItemGroupId = 1,
                            MaxPossessCount = 99,
                            Rarity = 1,
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500)
                        },
                        new
                        {
                            ItemId = 2,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500),
                            ItemGroupId = 1,
                            MaxPossessCount = 99,
                            Rarity = 2,
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500)
                        },
                        new
                        {
                            ItemId = 3,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500),
                            ItemGroupId = 2,
                            MaxPossessCount = 99,
                            Rarity = 5,
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3500)
                        });
                });

            modelBuilder.Entity("Api.Domain.Item.ItemGroup", b =>
                {
                    b.Property<int>("ItemGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemGroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ItemGroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ItemGroupId");

                    b.ToTable("m_item_group", (string)null);

                    b.HasData(
                        new
                        {
                            ItemGroupId = 1,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3480),
                            ItemGroupName = "回復薬",
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3480)
                        },
                        new
                        {
                            ItemGroupId = 2,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3480),
                            ItemGroupName = "武器",
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3480)
                        });
                });

            modelBuilder.Entity("Api.Domain.Item.ItemLocalize", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("ItemId");

                    b.ToTable("m_item_localize", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510),
                            ItemName = "アイテムテスト1",
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510)
                        },
                        new
                        {
                            ItemId = 2,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510),
                            ItemName = "アイテムテスト2",
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510)
                        },
                        new
                        {
                            ItemId = 3,
                            CreatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510),
                            ItemName = "アイテムテスト3",
                            UpdatedAt = new DateTime(2025, 11, 5, 17, 59, 52, 911, DateTimeKind.Utc).AddTicks(3510)
                        });
                });

            modelBuilder.Entity("Api.Domain.User.User", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("UserId");

                    b.ToTable("u_user", (string)null);
                });

            modelBuilder.Entity("Api.Domain.User.UserItem", b =>
                {
                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PossessCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("u_user_item", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Item.Item", b =>
                {
                    b.HasOne("Api.Domain.Item.ItemGroup", "ItemGroup")
                        .WithMany()
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_m_item__item_group_id");

                    b.Navigation("ItemGroup");
                });

            modelBuilder.Entity("Api.Domain.Item.ItemLocalize", b =>
                {
                    b.HasOne("Api.Domain.Item.Item", null)
                        .WithOne("ItemLocalize")
                        .HasForeignKey("Api.Domain.Item.ItemLocalize", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_m_item_localize__item_id");
                });

            modelBuilder.Entity("Api.Domain.User.UserItem", b =>
                {
                    b.HasOne("Api.Domain.Item.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_u_user_item__item_id");

                    b.HasOne("Api.Domain.User.User", null)
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_u_user_item__user_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Api.Domain.Item.Item", b =>
                {
                    b.Navigation("ItemLocalize")
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.User.User", b =>
                {
                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
